# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBue03ioFtAOYSQqTbPoJJMH9CpXL6LP
"""

import joblib
# ... (código inicial de streamlit)

# Cargar el modelo pre-entrenado de forma instantánea
modelo_ia = joblib.load('best_model.pkl')